### ISSUE TITLE
Add PHP logo

### ISSUE THREAD

**Issue by arogachev** [paper-cube/paper-cube.github.io#2]
How about adding PHP logo to the elephant?

**Comment by githubjeka** [comment]
What do you think, where it should be located?

**Comment by arogachev** [comment]
Right on the front of his body.

**Comment by githubjeka** [comment]
May it condemn us? (for the use of symbolism)

**Comment by githubjeka** [comment]
We need a lawyer to close this issue.

**Comment by lynicidn** [comment]
ду ю спик инглиш?

**Comment by githubjeka** [comment]
Use of the logo reveal the hidden meaning.
